### ISSUE TITLE
Problem with multi module project

### ISSUE THREAD

**Issue by jjvargas** [JeroenMols/ArtifactoryExample#1]
I have a project that has multiple modules, and I want to include the script in a separate file or in the master build.gradle so all the modules can use this.

I have a problem where it tries to get these variables, since they need to be defined locally

```
        groupId packageName
        version = libraryVersion
```

I tried something like

```
        def getLibraryVersion() {
            return module.hasProperty('libraryVersion') ? libraryVersion : "1.0.0"
        }
```

But its not picking up the correct value defined in the modules.

Any idea of what's going on?

**Comment by JeroenMols** [comment]
No sorry, struggeled with the same issue before andere finally resorted to using the Gradle.properties file. Completely due to my limited Gradle knowledge.

Let me know if you manage to sort this out.
Closing this issue because not directly related to this repo.
